line-length = 100
target-version = "py311"

[lint]
select = [
  "E", "F", "I", # pycodestyle/pyflakes/isort
  "B",           # flake8-bugbear
  "UP",          # pyupgrade
]
ignore = [
  "E501",  # handled by formatter
]

[lint.per-file-ignores]
"tests/*.py" = ["E402", "I001"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
